export interface BillboardSong {
	song: string;
	artist: string;
	this_week: number;
	last_week: number | null;
	peak_position: number;
	weeks_on_chart: number;
}

export interface BillboardChart {
	date: string;
	data: BillboardSong[];
}

/**
 * Get the ISO week number for a given date
 */
export function getISOWeek(date: Date): number {
	const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
	const dayNum = d.getUTCDay() || 7;
	d.setUTCDate(d.getUTCDate() + 4 - dayNum);
	const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
	return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
}

/**
 * Get the date of the first day (Monday) of a given ISO week
 */
export function getDateFromISOWeek(year: number, week: number): Date {
	const jan4 = new Date(year, 0, 4);
	const jan4Day = jan4.getDay() || 7;
	const firstMonday = new Date(jan4);
	firstMonday.setDate(jan4.getDate() - jan4Day + 1);
	const targetDate = new Date(firstMonday);
	targetDate.setDate(firstMonday.getDate() + (week - 1) * 7);
	return targetDate;
}

/**
 * Find the closest Billboard chart date to a target date
 */
export function findClosestChartDate(targetDate: Date, validDates: string[]): string | null {
	const targetTime = targetDate.getTime();
	let closestDate: string | null = null;
	let closestDiff = Infinity;

	for (const dateStr of validDates) {
		const chartDate = new Date(dateStr);
		const diff = Math.abs(chartDate.getTime() - targetTime);

		if (diff < closestDiff) {
			closestDiff = diff;
			closestDate = dateStr;
		}
	}

	return closestDate;
}

/**
 * Get the chart dates for a specific week across multiple years
 */
export function getChartDatesForWeek(
	week: number,
	startYear: number,
	endYear: number,
	validDates: string[]
): Map<number, string> {
	const chartDates = new Map<number, string>();

	// Group valid dates by year for faster lookup
	const datesByYear = new Map<number, string[]>();
	for (const dateStr of validDates) {
		const year = parseInt(dateStr.substring(0, 4));
		if (!datesByYear.has(year)) {
			datesByYear.set(year, []);
		}
		datesByYear.get(year)!.push(dateStr);
	}

	for (let year = startYear; year <= endYear; year++) {
		const yearDates = datesByYear.get(year);
		if (!yearDates || yearDates.length === 0) continue;

		const targetDate = getDateFromISOWeek(year, week);
		const closestDate = findClosestChartDate(targetDate, yearDates);

		if (closestDate) {
			chartDates.set(year, closestDate);
		}
	}

	return chartDates;
}

/**
 * Get current week number (next week by default)
 */
export function getNextWeekNumber(): number {
	const now = new Date();
	const currentWeek = getISOWeek(now);
	// Return next week, wrap around at year end
	return currentWeek >= 52 ? 1 : currentWeek + 1;
}

/**
 * Get the valid year range from the data
 */
export function getYearRange(validDates: string[]): { min: number; max: number } {
	if (validDates.length === 0) {
		return { min: 1958, max: new Date().getFullYear() };
	}

	const years = validDates.map((d) => parseInt(d.substring(0, 4)));
	return {
		min: Math.min(...years),
		max: Math.max(...years)
	};
}

/**
 * Format playlist name according to spec: BBT5WXYY-ZZ
 */
export function formatPlaylistName(week: number, startYear: number, endYear: number): string {
	const weekStr = week.toString().padStart(2, '0');
	const startStr = (startYear % 100).toString().padStart(2, '0');
	const endStr = (endYear % 100).toString().padStart(2, '0');
	return `BBT5W${weekStr}${startStr}-${endStr}`;
}

/**
 * Format playlist description
 */
export function formatPlaylistDescription(week: number, startYear: number, endYear: number): string {
	return `Billboard Top 5 for Week ${week}, years ${startYear}-${endYear}. Generated by Blast from the Past.`;
}

/**
 * Get previous chart dates before a given date (for streak calculation)
 * Returns dates in reverse chronological order (most recent first)
 */
export function getPreviousChartDates(
	currentDate: string,
	validDates: string[],
	maxCount: number = 52
): string[] {
	// Sort valid dates and find ones before current date
	const sortedDates = [...validDates].sort();
	const currentIndex = sortedDates.indexOf(currentDate);

	if (currentIndex <= 0) return [];

	// Get previous dates (most recent first)
	const previousDates: string[] = [];
	for (let i = currentIndex - 1; i >= 0 && previousDates.length < maxCount; i--) {
		previousDates.push(sortedDates[i]);
	}

	return previousDates;
}

/**
 * Calculate position change indicator
 * "new" = new to the top 5 (wasn't in top 5 last week or wasn't on chart at all)
 */
export function getPositionChange(
	thisWeek: number,
	lastWeek: number | null
): 'up' | 'down' | 'same' | 'new' {
	// New to top 5: wasn't on chart, or was outside top 5
	if (lastWeek === null || lastWeek > 5) return 'new';
	if (lastWeek > thisWeek) return 'up'; // lower number = higher position
	if (lastWeek < thisWeek) return 'down';
	return 'same';
}
